# This is a basic workflow to help you get started with Actions

name: EnvironmentProd


# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
     branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  
  branchCheck:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Check valid branch
        run: exit "only allowed to run this workflow for main branch"

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: branchCheck
    environment:
      name: build
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo "Environment name $envName"

      # Runs a set of commands using the runners shell
    - name: Run test script
      run: .\build_scripts\test.ps1 -clientId ${{ secrets.CLIENT_ID }}
      shell: pwsh
          
